version: 2

project_name: check

builds:
  - id: archives-unix
    main: .
    binary: check
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }}

  - id: archives-linux-extra
    main: .
    binary: check
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - loong64
      - mips64le
      - ppc64le
      - riscv64
      - s390x
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }}

  - id: linux-deb
    main: .
    binary: check
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }}
    hooks:
      post:
        - cmd: >-
            {{- if eq .Arch "arm64" -}}
            aarch64-linux-gnu-objcopy --remove-section .go.buildinfo "{{ .Path }}"
            {{- else -}}
            objcopy --remove-section .go.buildinfo "{{ .Path }}"
            {{- end -}}
          output: true

archives:
  - id: tarballs
    ids:
      - archives-unix
      - archives-linux-extra
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}
    files:
      - LICENSE
      - README.md

nfpms:
  - id: linux-packages
    ids:
      - linux-deb
    package_name: check
    formats:
      - deb
    file_name_template: >-
      {{ .PackageName }}_linux_{{ .Arch }}
    bindir: /usr/local/bin
    maintainer: JumpServer Dev <support@jumpserver.org>
    description: Health check tool for HTTP(S) and TCP endpoints.
    license: Apache 2.0
    homepage: https://github.com/jumpserver-dev/healthcheck

checksum:
  name_template: checksums.txt

changelog:
  disable: true
